"""initial schema: suppliers, users, purchase_orders, line_items

Revision ID: da9724f070a5
Revises:
Create Date: 2026-07-21 23:34:38.660051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import purchase_orders.infrastructure.db.models

# revision identifiers, used by Alembic.
revision: str = "da9724f070a5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column(
            "id", purchase_orders.infrastructure.db.models.GUID(), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tax_id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", purchase_orders.infrastructure.db.models.GUID(), nullable=False
        ),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column(
            "id", purchase_orders.infrastructure.db.models.GUID(), nullable=False
        ),
        sa.Column(
            "supplier_id",
            purchase_orders.infrastructure.db.models.GUID(),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("requested_by", sa.String(length=150), nullable=False),
        sa.Column("approved_by", sa.String(length=150), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "purchase_order_line_items",
        sa.Column(
            "id", purchase_orders.infrastructure.db.models.GUID(), nullable=False
        ),
        sa.Column(
            "purchase_order_id",
            purchase_orders.infrastructure.db.models.GUID(),
            nullable=False,
        ),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchase_order_line_items")
    op.drop_table("purchase_orders")
    op.drop_table("users")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
